{{- if .Values.deploymentConfig.sharedResources.enabled }}
{{/*
    IPfamily supported deployment (singlestack of choice or dualstack)
    Service options under service.external are used
    Service names has suffix of IPfamily
  */}}
{{ if or ( eq (include "eric-cbrs-dc.ext-service.enabled-IPv4" .) "true" ) (eq (include "eric-cbrs-dc.ext-service.enabled-IPv6" .) "true" ) }}
{{- if eq (include "eric-cbrs-dc.ext-service.enabled-IPv4" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-cbrs-dc.ext-service.name" . }}-ipv4
  labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
  annotations: {{- include "eric-cbrs-dc.ext-service.annotations-ipv4" . | nindent 4 }}
spec:
  ipFamilies: ["IPv4"]
{{- template "eric-cbrs-dc.ext-service.selector" . }}
{{- template "eric-cbrs-dc.ext-service.ports" . }}
  type: {{ .Values.service.externalService.type }}
{{- if .Values.service.externalService.externalIPv4.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.externalService.externalIPv4.loadBalancerIP }}
{{- end }}
{{- end }}
---
{{ if eq (include "eric-cbrs-dc.ext-service.enabled-IPv6" .) "true" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-cbrs-dc.ext-service.name" . }}-ipv6
  labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
  annotations: {{- include "eric-cbrs-dc.ext-service.annotations-ipv6" . | nindent 4 }}
spec:
  ipFamilies: ["IPv6"]
{{- template "eric-cbrs-dc.ext-service.selector" . }}
{{- template "eric-cbrs-dc.ext-service.ports" . }}
  type: {{ .Values.service.externalService.type }}
{{- if .Values.service.externalService.externalIPv6.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.externalService.externalIPv6.loadBalancerIP }}
{{- end }}
{{- end }}
{{/*
Legacy deployment with single service
Legacy service options are used
Service name has no ipFamily suffix
 */}}
{{ else }}
{{- if .Values.service.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-cbrs-dc.ext-service.name" . }}
  labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
  annotations: {{- include "eric-cbrs-dc.ext-service.annotations" . | nindent 4 }}
spec:
{{- template "eric-cbrs-dc.ext-service.selector" . }}
{{- template "eric-cbrs-dc.ext-service.ports" . }}
  type:  {{ .Values.service.externalService.type }}
{{- if .Values.service.externalService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.externalService.loadBalancerIP }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}