{{ if .Values.deploymentConfig.deploymentResources.enabled }}
# Below credentials are used to authenticate JBoss Console Management for eric-cbrs-dc
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}-jboss-secret
  labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
  annotations: {{- include "eric-cbrs-dc.annotations" . | nindent 4 }}
type: Opaque
data:
  # For jboss user
  jboss-user: {{ "YWRtaW4=" | quote }}
  # For jboss password
  jboss-password: {{ "b015SmFjKm9Kb0xYMHRFZjNyYXg0UG9yTXliYQ==" | quote }}
{{- end }}