{{- if or (eq (((.Values).global).log).streamingMethod "direct") (eq (((.Values).global).log).streamingMethod "dual") }}
  {{- include "eric-log-shipper-sidecar.logshipper-tls-cert-lt-client" . }}
{{- end }}