{{- if .Values.deploymentConfig.sharedResources.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ template "eric-cbrs-dc.name" . }}-read-services
 labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
 annotations:
  {{- $securityPolicy := include "eric-cbrs-dc.securityPolicy.annotations" . | fromYaml -}}
  {{- $default := include "eric-cbrs-dc.annotations" . | fromYaml -}}
  {{- include "eric-cbrs-dc.mergeAnnotations" (dict "location" .Template.Name "sources" (list $securityPolicy $default)) | trim | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ template "eric-cbrs-dc.name" . }}-read-services-binding
 labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
 annotations:
  {{- $securityPolicy := include "eric-cbrs-dc.securityPolicy.annotations" . | fromYaml -}}
  {{- $default := include "eric-cbrs-dc.annotations" . | fromYaml -}}
  {{- include "eric-cbrs-dc.mergeAnnotations" (dict "location" .Template.Name "sources" (list $securityPolicy $default)) | trim | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-cbrs-dc.name" . }}
roleRef:
 kind: Role
 name: {{ template "eric-cbrs-dc.name" . }}-read-services
 apiGroup: rbac.authorization.k8s.io
{{- end }}