{{- if .Values.deploymentConfig.sharedResources.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-cbrs-dc.name" . }}
  labels: {{- include "eric-cbrs-dc.labels" . | nindent 4 }}
  annotations: {{- include "eric-cbrs-dc.annotations" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}